version: '3'
services:
    outgame:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/outgame:latest
        container_name: outgame
        ports:
            - '8001:8001'
        environment:
            - PORT=8001
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
            - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
            - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
        depends_on:
            - redis
        env_file:
            - ./docker-compose.env

    ingame:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/ingame:latest
        container_name: ingame
        ports:
            - '8002:8002'
        environment:
            - PORT=8002
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - '6379:6379'
