const BOOST_PROB = 1
const SHIELD_PROB = 1
const THUNDER_PROB = 1
const GIFT_PROB = 1
const TOTAL_PROB = BOOST_PROB + SHIELD_PROB + THUNDER_PROB + GIFT_PROB
const ITEM_PICKUP_DISTANCE = 5
const SPEED_UP = 5
const ITEM_MAX_POS_Y = 5
const SPEED_DECREASE_FACTOR = 0.5

export const ITEM = {
    BOOST_PROB,
    SHIELD_PROB,
    THUNDER_PROB,
    GIFT_PROB,
    TOTAL_PROB,
    ITEM_PICKUP_DISTANCE,
    SPEED_UP,
    ITEM_MAX_POS_Y,
    SPEED_DECREASE_FACTOR,
}

export default ITEM
