const RABBIT_BASE_SPEED = 11
const SANTA_BASE_SPEED = 12
const GHOST_BASE_SPEED = 10
const ITEM_EVENT_BLOCK = 6
const TELEPORT_DISTANCE = 30
const SANTA_SKILL_SPEED = 6
export const CHARACTER = {
    RABBIT_BASE_SPEED,
    SANTA_BASE_SPEED,
    GHOST_BASE_SPEED,
    ITEM_EVENT_BLOCK,
    TELEPORT_DISTANCE,
    SANTA_SKILL_SPEED,
}
export default CHARACTER
