name: dev branch auto ci process script

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        steps:
            - name: executing remote ssh commands
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.REMOTE_IP }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_PRIVATE_KEY }}
                  port: ${{ secrets.REMOTE_SSH_PORT }}
                  script: |
                      cd /home/ubuntu/Server
                      git pull origin dev
                      pm2 kill
                      npm i --force
                      npm run prd
